### ISSUE TITLE
USXXMLBible.py

### ISSUE THREAD

**Issue by pomke** [openscriptures/BibleOrgSys#18]
```python
from USXXMLBible import USXXMLBible

b = USXXMLBible('Tests/DataFilesForTests/USXTest2')
b.load()
```

gives me:

```python
Traceback (most recent call last):
  File "rhema.py", line 4, in <module>
    b = USXXMLBible('Tests/DataFilesForTests/USXTest2')
  File "/Users/pomke/code/BibleOrgSys/USXXMLBible.py", line 168, in __init__
    Bible.__init__( self )
  File "/Users/pomke/code/BibleOrgSys/Bible.py", line 186, in __init__
    BibleWriter.__init__( self )
  File "/Users/pomke/code/BibleOrgSys/BibleWriter.py", line 148, in __init__
    ALL_CHAR_MARKERS = BibleOrgSysGlobals.USFMMarkers.getCharacterMarkersList( expandNumberableMarkers=True )
AttributeError: 'NoneType' object has no attribute 'getCharacterMarkersList'
```

And if I import BibleOrgSysGlobals then USFMMarkers is indeed Null..
and yet reading USXXMLBible.py demo section it looks like this should work? I tried downloading the XSF WEB from your website as well and just got the same issue using that folder. What am I doing wrong?

**Comment by RobH123** [comment]
Hi Pomke,
    
        This is the minimal program that will work:
    ProgName = "rhema"
      ProgVersion = "0.01"
      
      import BibleOrgSysGlobals
      from USXXMLBible import USXXMLBible
      
      parser = BibleOrgSysGlobals.setup( ProgName, ProgVersion
        )
      BibleOrgSysGlobals.addStandardOptionsAndProcess( parser )
      
      b = USXXMLBible('Tests/DataFilesForTests/USXTest2')
      b.load()
      
      BibleOrgSysGlobals.closedown( ProgName, ProgVersion )
    
    Then the run flags will also work: use --help to see them.
    python3 rhema.py --help
      
      usage: rhema.py [-h] [--version] [-s] [-q] [-i]
          [-v] [-e | -w] [-d] [-1] [-c]
        
        rhema v0.01
        
        optional arguments:
          -h, --help         show this help message and exit
          --version          show program's version number and
          exit
          -1, --single       don't use multiprocessing (that's
          the digit one)
          -c, --strict       perform very strict checking of
          all input
        
        Verbosity Group:
          Console verbosity controls
        
          -s, --silent       output no information to the
          console
          -q, --quiet        output less information to the
          console
          -i, --informative  output more information to the
          console
          -v, --verbose      output lots of information for the
          user
          -e, --errors       log errors to console
          -w, --warnings     log warnings and errors to console
      
    
    Blessings,
    Robert.
    
    On 09/07/16 01:14, Pomke Nohkan wrote:
    
    
      from USXXMLBible import USXXMLBible

b = USXXMLBible('Tests/DataFilesForTests/USXTest2')
b.load()

**Comment by pomke** [comment]
thank you!
